apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: student-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: student-app-app
  template:
    metadata:
      labels:
        app: student-app-app
    spec:
    containers:
      - name: nginx-container
        image: nginx:latest
        ports:
        - containerPort: 80