apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: student.app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: student.app
  template:
    metadata:
      labels:
        app: student.app
    spec:
    containers:
        - name: my-container
          image: nginx
          ports:
            - containerPort: 80 

        - name: tomcat-container
          image: tomcat
          ports: 
            - containerPort: 8080      